bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(
        '',
        views.all_products,
        name='products'),
    path(
        '<int:product_id>/',
        views.product_detail,
        name='product_detail'),
    path(
        'add/',
        views.add_product,
        name='add_product'),
    path(
        'edit/<int:product_id>/',
        views.edit_product,
        name='edit_product'),
    path(
        'delete/<int:product_id>/',
        views.delete_product,
        name='delete_product'),
]

z_v_gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile


# Order Form by The Code Institute
class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=False,
        default=0)
    grand_total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=False,
        default=0)
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254,
        null=False,
        blank=False,
        default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time an item is added.
        """
        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total'))['lineitem_total__sum'] or 0
        self.delivery_cost = self.order_total * \
            settings.STANDARD_DELIVERY_PERCENTAGE / 100
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it has not been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(
        Order,
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        related_name='lineitems')
    product = models.ForeignKey(
        Product,
        null=False,
        blank=False,
        on_delete=models.CASCADE)
    product_frame = models.CharField(max_length=5, null=True, blank=True)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=False,
        blank=False,
        editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'order number: {self.order.order_number}'

products/models.py
from django.db import models


class Project(models.Model):
    friendly_name = models.CharField(max_length=254)
    name = models.CharField(max_length=254)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.friendly_name

    def get_name(self):
        return self.name


class Product(models.Model):
    project = models.ForeignKey('Project', null=True, blank=True,
                                on_delete=models.SET_NULL)
    name = models.CharField(max_length=254)
    description = models.TextField()
    framed = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(max_digits=4, decimal_places=1,
                                 null=True, blank=True)
    image1 = models.ImageField(null=True, blank=True)
    image2 = models.ImageField(null=True, blank=True)
    image3 = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .models import Product, Project


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        projects = Project.objects.all()
        names = [(p.id, p.__str__()) for p in projects]

        self.fields['project'].choices = names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black'

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from reviews.models import Review
from reviews.forms import ReviewForm

from .models import Product, Project
from .forms import ProductForm


def all_products(request):
    """ A view to show each product details """

    products = Product.objects.all().order_by('project')
    query = None
    projects = None

    if request.GET:
        if 'project' in request.GET:
            projects = request.GET['project'].split(',')
            products = products.filter(project__name__in=projects)
            projects = Project.objects.filter(name__in=projects)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(
                    request, "You did not enter any search criteria!")
                return redirect(reverse('products'))

            queries = Q(
                name__icontains=query) | Q(
                description__icontains=query)
            products = products.filter(queries)

    context = {
        'products': products,
        'search_term': query,
        'current_projects': projects,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to show all products """

    product = get_object_or_404(Product, pk=product_id)
    reviews = Review.objects.filter(product=product)
    review_form = ReviewForm()

    context = {
        'product': product,
        'reviews': reviews,
        'form': review_form,
    }

    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, access for store owners only.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request,
                'Failed to add product. Please ensure the form is valid.')
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, access for store owners only.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request,
                'Failed to update product. Please ensure the form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """ Delete a product from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, access for store owners only.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- Add Product Form -->
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3 text-center mt-3">
            <h2 class="mb-2">Product Management</h2>
            <hr class="w-50">
            <h5 class="text-muted mb-5">Add a Product</h5>
        </div>
    </div>
    <div class="row">
        <div class="col-10 offset-1 col-lg-6 offset-lg-3 product-management-form mb-5">
            <div class="mt-5 mb-1">
                <h6 class="text-center">To Add new product, fill out the form below.</h6>
                <small class="text-muted"><i>* is a required field</i></small>
            </div>
            <form method="POST" action="{% url 'add_product' %}" class="form mb-3" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="text-center">
                    <a href="{% url 'products' %}" class="btn btn-outline-dark">Cancel</a>
                    <button class="btn btn-success" type="submit">Add Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- Edit Product Form -->
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3 text-center mt-3">
            <h2 class="mb-2">Product Management</h2>
            <hr class="w-50">
            <h5 class="text-muted mb-5">Edit a Product</h5>
        </div>
    </div>
    <div class="row">
        <div class="col-10 offset-1 col-lg-6 offset-lg-3 product-management-form p-3 mb-5">
            <div class="mt-5 mb-1">
                <h6 class="text-center">To Edit a product, fill out the form below.</h6>
                <small class="text-muted"><i>* is a required field</i></small>
            </div>
            <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-3"
                enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="text-center">
                    <a href="{% url 'products' %}" class="btn btn-outline-dark">Cancel</a>
                    <button class="btn btn-success" type="submit">Save Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 col-md-4 text-left mt-2">
            <a href="{% url 'products' %}" class="btn btn-sm btn-outline-dark mb-5">
                <span class="icon">
                    <i class="fas fa-long-arrow-alt-left"></i>
                </span>
                <span class="text-uppercase">Back to Shop</span>
            </a>
        </div>
        <div class="col-12 col-md-4 text-center mt-3">
            <h2 class="logo-font">Details</h2>
            <hr class="w-50 mb-1">
        </div>
        <div class="col-12 col-md-4"></div>
    </div>
    <div class="row text-center">
        <div class="col-12 product-name-container mb-3 mt-5">
            <h3 class="mb-0">{{ product.name }}</h3>
        </div>
        <div class="col-12 product-details-container mb-3 mt-2">
            <p class="mt-3">{{ product.description }}</p>
        </div>
    </div>
    <!-- Product Images -->
    <div class="row text-center">
        <div class="col-12 col-lg-4 mb-5 mt-5">
            {% if product.image2 %}
            <a href="{{ product.image2.url }}" target="_blank">
                <img class="col-lg-10 col-sm-8" src="{{ product.image2.url }}" alt="{{ product.name }}">
            </a>
            {% endif %}
        </div>
        <div class="col-12 col-lg-4 mb-5 mt-5">
            {% if product.image1 %}
            <a href="{{ product.image1.url }}" target="_blank">
                <img class="col-lg-10 col-sm-8" src="{{ product.image1.url }}" alt="{{ product.name }}">
            </a>
            {% else %}
            <img class="col-lg-10 col-sm-8" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
            {% endif %}
        </div>
        <div class="col-12 col-lg-4 mb-5 mt-5">
            {% if product.image3 %}
            <a href="{{ product.image3.url }}" target="_blank">
                <img class="col-lg-10 col-sm-8" src="{{ product.image3.url }}" alt="{{ product.name }}">
            </a>
            {% endif %}
        </div>
    </div>
    <div class="row text-center">
        {% if request.user.is_superuser %}
        <div class="col-6 offset-3">
            <small>
                <a class="mb-2 text-warning" href="{% url 'edit_product' product.id %}">Edit</a> |
            <!-- Trigger Modal From Bootstrap 4.4 -->
                <a class="mb-2 text-danger remove-item" data-toggle="modal" data-target="#productDeleteModal">Delete</a>
            </small>
            <!-- Modal From Bootstrap 4.4 -->
            <div class="modal fade" id="productDeleteModal" tabindex="-1" role="dialog"
                aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content text-center">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            </button>
                        </div>
                        <div class="modal-body">
                            <h6 class="text-dark">Are you sure you want to
                                delete this product?
                            </h6>
                        </div>
                        <div class="modal-footer d-flex justify-content-between">
                            <button type="button" class="btn btn-outline-dark text-uppercase" data-dismiss="modal">
                                <span class="icon">
                                    <i class="fas fa-long-arrow-alt-left"></i>
                                </span>
                                <span class="text-uppercase">Back</span>
                            </button>
                            <a href="{% url 'delete_product' product.id %}" type="button"
                                class="btn btn-outline-danger text-uppercase">
                                Delete
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        <div class="col-12 mb-3">
            <hr class="w-50">
            <p class="lead font-weight-bold">${{ product.price }}</p>
        </div>
        <div class="col-12 mb-3">
            {% if product.rating %}
            <small class="text-muted"><i class="fas fa-star mr-1 text-warning"></i>{{ product.rating }} / 5</small>
            {% else %}
            <small class="text-muted">No Rating</small>
            {% endif %}
        </div>
    </div>
    <!-- Add Product to the Shopping bag Form by Code Institute -->
    <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST">
        {% csrf_token %}
        <div class="row text-center">
            {% with product.framed as white %}
            {% if white %}
            <div class="col-6 offset-3 col-md-2 offset-md-5 mb-3">
                <p><strong>Frame:</strong></p>
                <select name="product_frame" id="id_product_frame" class="form-control">
                    <option value="no">Unframed</option>
                    <option value="white">White</option>
                    <option value="black">Black</option>
                </select>
            </div>
            {% endif %}
            {% endwith %}
        </div>
        <div class="row text-center">
            <div class="col-6 offset-3 col-md-2 offset-md-5 mb-3">
                <p class="mt-3"><strong>Quantity:</strong></p>
                <!-- Plus Minus quantity buttons by The Code Institute. Thanks -->
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <button class="decrement-qty btn rounded-0" data-item_id="{{ product.id }}"
                                id="decrement-qty_{{ product.id }}">
                                <span class="icon">
                                    <i class="fas fa-minus"></i>
                                </span>
                            </button>
                        </div>
                        <input class="form-control qty_input" type="number" name="quantity" value="1" min="1" max="99"
                            data-item_id="{{ product.id }}" id="id_qty_{{ product.id }}">
                        <div class="input-group-append">
                            <button class="increment-qty btn rounded-0" data-item_id="{{ product.id }}"
                                id="increment-qty_{{ product.id }}">
                                <span class="icon">
                                    <i class="fas fa-plus"></i>
                                </span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Keep Shopping and Add to Bag -->
        <div class="row text-center">
            <div class="col-12">
                <a href="{% url 'products' %}" class="btn btn-outline-dark mb-5">
                    <span class="icon">
                        <i class="fas fa-long-arrow-alt-left"></i>
                    </span>
                    <span class="text-uppercase">Keep Shopping</span>
                </a>
                <input type="submit" class="btn btn-success text-uppercase mb-5" value="+ Add to Bag">
            </div>
            <input type="hidden" name="redirect_url" value="{{ request.path }}">
        </div>
    </form>
</div>
<hr>
<!-- Product Reviews Section -->
{% include 'reviews/includes/reviews.html' %}

{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}

products/templates/products/products.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mb-5">
    <div class="row">
        <div class="col text-center mt-3">
            <h2 class="mb-2">Prints</h2>
            <hr class="w-50 mb-1">
        </div>
    </div>
    <div class="row">
        <!-- View by Project Dropdown -->
        <div class="col-3 ml-4 mr-0">
            <ul class="list-inline list-unstyled text-center">
                <li class="list-inline-item dropdown">
                    <a class="text-black nav-link" href="#" id="user-options" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        <div class="text-center">
                            <div><i class="fas fa-camera-retro"></i></div>
                            <h6 class="my-0 d-none d-md-block">View by Project</h6>
                            <h6 class="d-block d-sm-block d-md-none">Projects</h6>
                            <div><i class="fas fa-sort-down"></i></div>
                        </div>
                    </a>
                    <div class="dropdown-menu border-0" aria-labelledby="user-options">
                        <a href="{% url 'products' %}?project=in_the_bath" class="dropdown-item">In the Bath</a>
                        <a href="{% url 'products' %}?project=ginger" class="dropdown-item">Ginger</a>
                        <a href="{% url 'products' %}?project=vogue" class="dropdown-item">Vogue</a>
                        <a href="{% url 'products' %}?project=collages" class="dropdown-item">Collages</a>
                        <a href="{% url 'products' %}" class="dropdown-item">All Projects</a>
                    </div>
                </li>
            </ul>
        </div>
        <!-- Search Prints Form -->
        <div class="col-6 mt-3">
            <form method="GET" action="{% url 'products' %}">
                <div class="input-group w-100">
                    <input class="form-control border border-black rounded-0" type="text" name="q"
                        placeholder="Search...">
                    <div class="input-group-append">
                        <button class="form-control btn border border-black rounded-0" type="submit">
                            <span class="icon">
                                <i class="fas fa-search"></i>
                            </span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
    <!-- All Prints -->
    <div class="row mt-3">
        <div id="product-container" class="col-10 offset-1">
            <div class="row mt-1 mb-1"></div>
            <div class="row">
                {% for product in products %}
                <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                    <div class="card h-100 border-0">
                        {% if product.image1 %}
                        <a href="{% url 'product_detail' product.id %}">
                            <img class="card-img-top img-fluid" src="{{ product.image1.url }}" alt="{{ product.name }}">
                        </a>
                        {% else %}
                        <a href="{% url 'product_detail' product.id %}">
                            <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png"
                                alt="{{ product.name }}">
                        </a>
                        {% endif %}
                        <div class="card-body pb-0">
                            <p class="mb-0 font-weight-bold">{{ product.name }}</p>
                        </div>
                        <div class="card-body pb-0">
                            <p class="mb-0">{{ product.project }}</p>
                        </div>
                        <div class="card-footer bg-white pt-0 border-0 text-left">
                            <div class="row">
                                <div class="col">
                                    <p class="lead mb-0 text-left font-weight-bold">${{ product.price }}</p>
                                    {% if product.rating %}
                                    <small class="text-muted"><i
                                            class="fas fa-star text-warning mr-1"></i>{{ product.rating }} /
                                        5</small>
                                    {% else %}
                                    <small class="text-muted mb-5">No Rating</small>
                                    {% endif %}
                                    {% if request.user.is_superuser %}
                                    <small class="ml-3">
                                        <a class="text-warning" href="{% url 'edit_product' product.id %}">Edit</a>
                                    </small>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Thanks to The Code Institute for a great example of cards separation -->
                {% if forloop.counter|divisibleby:1 %}
                <div class="col-12 d-sm-none mb-3">
                    <hr>
                </div>
                {% endif %}
                {% if forloop.counter|divisibleby:2 %}
                <div class="col-12 d-none d-sm-block d-md-block d-lg-none mb-3">
                    <hr>
                </div>
                {% endif %}
                {% if forloop.counter|divisibleby:3 %}
                <div class="col-12 d-none d-lg-block d-xl-none mb-3">
                    <hr>
                </div>
                {% endif %}
                {% if forloop.counter|divisibleby:4 %}
                <div class="col-12 d-none d-xl-block mb-3">
                    <hr>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<!-- Back to the Top button -->
<div class="to-top-button">
    <a class="to-top-button-link">
        <i class="fas fa-angle-double-up" title="Back To Top"></i>
    </a>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script>
    $('.to-top-button-link').click(function (e) {
        window.scrollTo(0, 0);
    });
</script>
{% endblock %}